GET https://api.pkk.bigland.ru/test/plots HTTP/1.1
content-type: application/json

{
    "collection": {
        "plots": [
            "69:27:0000022:1306",
            "69:27:0000022:1307"
        ]
    }
}

###

GET http://test-front/rest HTTP/1.1